<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>PiltiSmart - Privacy </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="" />
    <meta name="author" content="http://webthemez.com" />

    <link href="css/bootstrap.min.css" rel="stylesheet" />
    <link href="css/fancybox/jquery.fancybox.css" rel="stylesheet">
    <link href="css/jcarousel.css" rel="stylesheet" />
    <link href="css/flexslider.css" rel="stylesheet" />
    <link href="css/style.css" rel="stylesheet" />

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

</head>

<body>
    <div id="wrapper">

        <!-- start header -->
        <header>
            <div class="navbar navbar-default navbar-static-top">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse"
                            data-target=".navbar-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="index.php"><img src="img/logo.png" alt="logo" /></a>
                    </div>
                    <div class="navbar-collapse collapse ">
                        <ul class="nav navbar-nav">
                            <li><a href="index.php">Home</a></li>
                            <li><a href="about.php">About Us</a></li>
                            <li class="active"><a href="services.php">Services</a></li>
                            <li><a href="pricing.php">Pricing</a></li>
                            <li><a href="contact.php">Contact</a></li>
                            <li><a href="pilticloud.php">PiltiSmart Cloud</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </header><!-- end header -->
        <section id="content">
            <div class="container content">


                <h1 class="header-display-l">Privacy Policy</h1>


                <!-- article -->
                <article id="post-9" class="post-9 page type-page status-publish hentry">

                    <div class="at-above-post-page addthis_tool" data-url="https://design.org/privacy-policy/"></div>
                    <p>Our Privacy Policy was last updated on 18 June 2021. It governs the privacy terms of our
                        website, located at PiltiSmart.com, and the tools and forms we provide you (the “Website” or the
                        “Service”).</p>



                    <h2>YOUR PRIVACY</h2>



                    <p>Our Website follows all legal requirements to protect your privacy. Our Privacy Policy is a legal
                        statement that explains how we may collect information from you, how we may share your
                        information, and how you can limit our sharing of your information. You will see terms in our
                        Privacy Policy that are capitalized. These terms have meanings as described in the Definitions
                        section below.</p>



                    <h2>DEFINITIONS</h2>



                    <ul>
                        <li>Personal Data: Personal Data means data about a living individual who can be identified from
                            those data (or from those and other information either in our possession or likely to come
                            into our possession).</li>
                        <li>Usage Data: Usage Data is data collected automatically either generated by the use of the
                            Service or from the Service infrastructure itself </li>
                        <li>Cookies: Cookies are small pieces of data stored on a User’s device.</li>
                        <li>Data Controller: Data Controller means a natural or legal person who (either alone or
                            jointly or in common with other persons) determines the purposes for which and the manner in
                            which any personal data are, or are to be, processed. For the purpose of this Privacy
                            Policy, we are a Data Controller of your data.</li>
                        <li>Data Processors (or Service Providers): Data Processor (or Service Provider) means any
                            natural or legal person who processes the data on behalf of the Data Controller. We may use
                            the services of various Service Providers in order to process your data more effectively.
                        </li>
                        <li>Data Subject: Data Subject is any living individual who is the subject of Personal Data.
                        </li>
                        <li>User: The User is the individual using our Service. The User corresponds to the Data
                            Subject, who is the subject of Personal Data.</li>
                    </ul>



                    <h2>INFORMATION COLLECTION AND USE</h2>



                    <p>We collect several different types of information for various purposes to provide and improve our
                        Service to you.</p>



                    <h2>TYPES OF DATA COLLECTED</h2>



                    <h3>Personal Data</h3>



                    <ul>
                        <li>While using our Service, we may ask you to provide us with certain personally identifiable
                            information that can be used to contact or identify you (“Personal Data”). Personally
                            identifiable information may include, but is not limited to: Email address, Phone, Name,
                            Address, State, Province, ZIP/Postal code, City, Cookies and Usage Data.</li>
                        <li>We may use your Personal Data to contact you with newsletters, marketing or promotional
                            materials and other information that may be of interest to you. You may opt out of receiving
                            any, or all, of these communications from us by following the unsubscribe link or
                            instructions provided in any email we send.</li>
                    </ul>



                    <h3>Usage Data</h3>



                    <ul>
                        <li>We may also collect information how the Service is accessed and used (“Usage Data”). This
                            Usage Data may include information such as your computer’s Internet Protocol address (e.g.
                            IP address), browser type, browser version, the pages of our Service that you visit, the
                            time and date of your visit, the time spent on those pages, unique device identifiers and
                            other diagnostic data.</li>
                    </ul>



                    <h3>Tracking &amp; Cookies Data</h3>



                    <ul>
                        <li>We use cookies and similar tracking technologies to track the activity on our Service and
                            hold certain information.</li>
                        <li>Cookies are files with small amount of data which may include an anonymous unique
                            identifier. Cookies are sent to your browser from a website and stored on your device.
                            Tracking technologies also used are beacons, tags, and scripts to collect and track
                            information and to improve and analyze our Service.</li>
                        <li>You can instruct your browser to refuse all cookies or to indicate when a cookie is being
                            sent. However, if you do not accept cookies, you may not be able to use some portions of our
                            Service.</li>
                        <li>Examples of Cookies we use: session cookies (we use these cookies to operate our Service)
                            and preference cookies (we use these cookies to remember your preferences and various
                            settings).</li>
                    </ul>



                    <h3>Use of Data</h3>



                    <p>We use the collected data for various purposes:</p>



                    <ul>
                        <li>To provide and maintain our Service</li>
                        <li>To notify you about changes to our Service</li>
                        <li>To allow you to participate in interactive features of our Service when you choose to do so
                        </li>
                        <li>To provide customer support</li>
                        <li>To gather analysis or valuable information so that we can improve our Service</li>
                        <li>To monitor the usage of our Service</li>
                        <li>To detect, prevent and address technical issues</li>
                        <li>To provide you with news, special offers and general information about other goods, services
                            and events which we offer that are similar to those that you have already purchased or
                            enquired about unless you have opted not to receive such information</li>
                    </ul>



                    <h2>RETENTION OF DATA</h2>



                    <p>We will retain your Personal Data only for as long as is necessary for the purposes set out in
                        this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply
                        with our legal obligations (for example, if we are required to retain your data to comply with
                        applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>



                    <p>We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained
                        for a shorter period of time, except when this data is used to strengthen the security or to
                        improve the functionality of our Service, or we are legally obligated to retain this data for
                        longer time periods.</p>



                    <h2>TRANSFER OF DATA</h2>



                    <p>Your information, including Personal Data, may be transferred to — and maintained on — computers
                        located outside of your state, province, country or other governmental jurisdiction where the
                        data protection laws may differ than those from your jurisdiction.</p>



                    <p>We will take all steps reasonably necessary to ensure that your data is treated securely and in
                        accordance with this Privacy Policy and no transfer of your Personal Data will take place to an
                        organization or a country unless there are adequate controls in place including the security of
                        your data and other personal information.</p>



                    <p>Your consent to this Privacy Policy followed by your submission of such information represents
                        your agreement to that transfer.</p>



                    <h2>DISCLOSURE OF DATA</h2>



                    <ul>
                        <li>Business Transaction. If we are involved in a merger, acquisition or asset sale, your
                            Personal Data may be transferred. We will provide notice before your Personal Data is
                            transferred and becomes subject to a different Privacy Policy.</li>
                        <li>Disclosure for Law Enforcement. Under certain circumstances, we may be required to disclose
                            your Personal Data if required to do so by law or in response to valid requests by public
                            authorities (e.g. a court or a government agency).</li>
                    </ul>



                    <h2>SECURITY OF DATA</h2>



                    <p>The security of your data is important to us, but remember that no method of transmission over
                        the Internet, or method of electronic storage is 100% secure. While we strive to use
                        commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute
                        security.</p>



                    <h2>LEGAL BASIS FOR PROCESSING PERSONAL DATA UNDER GENERAL DATA PROTECTION REGULATION (GDPR)</h2>



                    <p>If you are from the European Economic Area (EEA), PiltiSmart.com legal basis for collecting and using
                        the personal information described in this Privacy Policy depends on the Personal Data we
                        collect and the specific context in which we collect it.</p>



                    <p>PiltiSmart.com may process your Personal Data because:</p>



                    <ul>
                        <li>We need to perform a contract with you</li>
                        <li>You have given us permission to do so</li>
                        <li>The processing is in our legitimate interests and it’s not overridden by your rights</li>
                        <li>For payment processing purposes</li>
                        <li>To comply with the law</li>
                    </ul>



                    <h2>YOUR DATA PROTECTION RIGHTS UNDER GENERAL DATA PROTECTION REGULATION (GDPR)</h2>



                    <p>If you are a resident of the European Economic Area (EEA), you have certain data protection
                        rights. PiltiSmart.com aims to take reasonable steps to allow you to correct, amend, delete, or
                        limit the use of your Personal Data.</p>



                    <p>If you wish to be informed what Personal Data we hold about you and if you want it to be removed
                        from our systems, please contact us.</p>



                    <p>In certain circumstances, you have the following data protection rights:</p>



                    <ul>
                        <li>The right to access, update or to delete the information we have on you.</li>
                        <li>The right of rectification. You have the right to have your information rectified if that
                            information is inaccurate or incomplete.</li>
                        <li>The right to object. You have the right to object to our processing of your Personal Data.
                        </li>
                        <li>The right of restriction. You have the right to request that we restrict the processing of
                            your personal information.</li>
                        <li>The right to data portability. You have the right to be provided with a copy of your
                            Personal Data in a structured, machine-readable and commonly used format.</li>
                        <li>The right to withdraw consent. You also have the right to withdraw your consent at any time
                            where PiltiSmart.com relied on your consent to process your personal information.</li>
                    </ul>



                    <p>Please note that we may ask you to verify your identity before responding to such requests.</p>



                    <p>You have the right to complain to a Data Protection Authority about our collection and use of
                        your Personal Data. For more information, please contact your local data protection authority in
                        the European Economic Area (EEA).</p>



                    <h2>SERVICE PROVIDERS</h2>



                    <p>We may employ third party companies and individuals to facilitate our Service (“Service
                        Providers”), to provide the Service on our behalf, to perform Service-related services or to
                        assist us in analyzing how our Service is used.</p>



                    <p>These third parties have access to your Personal Data only to perform these tasks on our behalf
                        and are obligated not to disclose or use it for any other purpose.</p>



                    <h2>TRACKING &amp; ANALYTICS</h2>



                    <p>We may use third-party Service Providers to monitor and analyze the use of our Service.</p>



                    <h3>Google Analytics</h3>



                    <p>Google Analytics is a web analytics service offered by Google that tracks and reports website
                        traffic. Google uses the data collected to track and monitor the use of our Service. This data
                        is shared with other Google services. Google may use the collected data to contextualize and
                        personalize the ads of its own advertising network.</p>



                    <p>You can opt-out of having made your activity on the Service available to Google Analytics by
                        installing the Google Analytics opt-out browser add-on. The add-on prevents the Google Analytics
                        JavaScript (ga.js, analytics.js, and dc.js) from sharing information with Google Analytics about
                        visits activity.</p>



                    <p>For more information on the privacy practices of Google, please visit the Google Privacy &amp;
                        Terms web page: http://www.google.com/intl/en/policies/privacy/</p>



                    <!-- <h3>Segment</h3>



                    <p>Segment is a event tracking tool used to track user actions to inform product decisions.</p>



                    <p>For more information on the privacy practices of Segment, please visit the Segment Privacy &amp;
                        Terms web page: https://segment.com/docs/legal/privacy/</p>



                    <h3>SendGrid</h3>



                    <p>SendGrid is an email distribution tool used to send email to users</p>



                    <p>For more information on the privacy practices of SendGrid, please visit the SendGrid Privacy
                        &amp; Terms web pages: https://sendgrid.com/policies/tos/</p> -->



                    <h3>Twillio</h3>



                    <p>Twillio is an SMS distribution tool used to send SMS messages to users</p>



                    <p>For more information on the privacy practices of Twillio, please visit the Twillio Privacy &amp;
                        Terms web pages: https://www.twilio.com/legal/tos</p>



                    <!-- <h2>PAYMENTS</h2>



                    <p>We may provide paid products and/or services within the Service. In that case, we use third-party
                        services for payment processing (e.g. payment processors).</p>



                    <p>We will not store or collect your payment card details. That information is provided directly to
                        our third-party payment processors whose use of your personal information is governed by their
                        Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by
                        the PCI Security Standards Council, which is a joint effort of brands like Visa, Mastercard,
                        American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment
                        information.</p>



                    <p>The payment processors we work is Stripe. Their Privacy Policy can be viewed at
                        https://stripe.com/us/privacy</p> -->



                    <h2>LINKS TO OTHER SITES</h2>



                    <p>Our Service may contain links to other sites that are not operated by us. If you click on a third
                        party link, you will be directed to that third party’s site. We strongly advise you to review
                        the Privacy Policy of every site you visit.</p>



                    <p>We have no control over and assume no responsibility for the content, privacy policies or
                        practices of any third party sites or services.</p>



                    <h2>CHILDREN’S PRIVACY</h2>



                    <p>Our Service does not address anyone under the age of 18 (“Children”).</p>



                    <p>We do not knowingly collect personally identifiable information from anyone under the age of 18.
                        If you are a parent or guardian and you are aware that your Children has provided us with
                        Personal Data, please contact us. If we become aware that we have collected Personal Data from
                        children without verification of parental consent, we take steps to remove that information from
                        our servers.</p>



                    <h2>CHANGES TO THIS PRIVACY POLICY</h2>



                    <p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting
                        the new Privacy Policy on this page.</p>



                    <p>We will let you know via email and/or a prominent notice on our Service, prior to the change
                        becoming effective and update the “effective date” at the top of this Privacy Policy.</p>



                    <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this
                        Privacy Policy are effective when they are posted on this page.</p>



                    <h2>CONTACT US</h2>



                    <p>If you have any questions or would like to notify us regarding this Privacy Policy, please
                        contact us by emailing <a href="/cdn-cgi/l/email-protection" class="__cf_email__"
                            data-cfemail="721a171e1e1d321617011b151c5c1d0015">[email&#160;protected]</a></p>
                    <!-- AddThis Advanced Settings above via filter on the_content -->
                    <!-- AddThis Advanced Settings below via filter on the_content -->
                    <!-- AddThis Advanced Settings generic via filter on the_content -->
                    <!-- AddThis Share Buttons above via filter on the_content -->
                    <!-- AddThis Share Buttons below via filter on the_content -->
                    <div class="at-below-post-page addthis_tool" data-url="https://design.org/privacy-policy/"></div>
                    <!-- AddThis Share Buttons generic via filter on the_content -->


                </article>
                <!-- /article -->



        </section>
        <!-- /section -->



    </div>
    </section>
    <?php include_once 'footer.php';?>
    </div>
    <a href="#" class="scrollup"><i class="fa fa-angle-up active"></i></a>
    <!-- javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="js/jquery.js"></script>
    <script src="js/jquery.easing.1.3.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/jquery.fancybox.pack.js"></script>
    <script src="js/jquery.fancybox-media.js"></script>
    <script src="js/portfolio/jquery.quicksand.js"></script>
    <script src="js/portfolio/setting.js"></script>
    <script src="js/jquery.flexslider.js"></script>
    <script src="js/animate.js"></script>
    <script src="js/custom.js"></script>
</body>

</html>